# Use an official Node.js, and it should be version 16 and above
FROM node:lts-bullseye-slim
# Set the working directory in the container
WORKDIR /api
# Copy package.json and pnpm-lock.yaml
COPY ../ ./
RUN npm i -g @nestjs/cli

# Install dependencies
RUN npm install
# Build the TypeScript code
RUN npm build
# Expose the app
EXPOSE 5000
# Start the application
CMD ["npm", "start"]